version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  app:
    build: .
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=your_connection_string
    depends_on:
      - kafka
    command: python producer.py
    # To run consumer or dashboard, override the command:
    # command: python consumer_for_vehicle.py
    # command: python vehicle.py 